/*
 * File: app/store/worditemStore.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.worditemStore', {
    extend: 'Ext.data.Store',

    requires: [
        'MyApp.model.worditemModel',
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Json'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            model: 'MyApp.model.worditemModel',
            storeId: 'worditemStore',
            pageSize: 10,
            proxy: {
                type: 'ajax',
                url: '../worditemsentence.action',
                reader: {
                    type: 'json',
                    root: 'root'
                }
            },
            listeners: {
                beforeload: {
                    fn: me.onJsonstoreBeforeLoad,
                    scope: me
                }
            }
        }, cfg)]);
    },

    onJsonstoreBeforeLoad: function(store, operation, eOpts) {
        var worditem = Ext.getCmp("tfworditem").getValue().replace(new RegExp(' ','g'),'%');
        worditem =  toSimp(worditem);
        var worditemprecise = Ext.getCmp("ckworditemprecise").getValue();
        var iscurrentwordclass = Ext.getCmp("ckcwordclass").getValue();
        var worditemtype = Ext.getCmp("cbworditemtype").getValue();
        var citycode = Ext.getCmp("selectcity").submitValue;
        this.proxy.actionMethods = "post";
        this.proxy.extraParams = {
            action: 'select',
            worditem: worditem,
            worditemprecise: worditemprecise,
            iscurrentwordclass: iscurrentwordclass,
            worditemtype: worditemtype,
            curwordclass: curwordclass,
            citycode: citycode
        };

        /*正则表达式 替换括号,尖括号等*/
        	function toSimp(str) {
                var RexStr = /\!|\<|\>|\[|\]/g;
        		str=str.replace(/\>\<|\>\[|\]\<|\]\[|\-|\|/g,"*");
        		str = str.replace(RexStr, "");
                RexStr = /\*/g;
                str = str.replace(RexStr, "%");
                //str=str.replace(/\@\[1|2\]\#|\#\[有序|无序\]\#/g,"%");
        		return str;
        	}

    }

});