/*
 * File: app/store/wordclassStore.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.wordclassStore', {
    extend: 'Ext.data.Store',

    requires: [
        'MyApp.model.wordclassModel',
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Json'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            model: 'MyApp.model.wordclassModel',
            storeId: 'wordclassStore',
            pageSize: 10,
            proxy: {
                type: 'ajax',
                timeout: 300000,
                url: '../wordclass.action',
                reader: {
                    type: 'json',
                    root: 'root'
                }
            },
            listeners: {
                beforeload: {
                    fn: me.onJsonstoreBeforeLoad,
                    scope: me
                }
            }
        }, cfg)]);
    },

    onJsonstoreBeforeLoad: function(store, operation, eOpts) {
        var wordclass = Ext.getCmp("tfwordclass").getValue().replace(new RegExp(' ','g'),'');
        var wordclassprecise = Ext.getCmp("ckwordclassprecise").getValue();
        var cbwordclasstypeselect = Ext.getCmp("cbwordclasstypeselect").getValue();
        if(cbwordclasstypeselect==null||cbwordclasstypeselect==""){
        cbwordclasstypeselect="全部";
        }
        //alert(cbwordclasstypeselect);
        Ext.getCmp('worditemgridpanel').store.removeAll();//清空词条列表
        this.proxy.actionMethods = "post";
        this.proxy.extraParams = { action: 'select', wordclass:wordclass,wordclassprecise:wordclassprecise,wordclasstype:cbwordclasstypeselect};
    }

});