package com.knowology.km.AnswerFindClient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "AnswerFinderServiceDelegate", targetNamespace = "http://Services.AnswerFinderWebService.knowology.com/")
public interface AnswerFinderServiceDelegate {

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "FindAnswer")
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "FindAnswer", targetNamespace = "http://Services.AnswerFinderWebService.knowology.com/", className = "com.knowology.km.AnswerFindClient.FindAnswer")
	@ResponseWrapper(localName = "FindAnswerResponse", targetNamespace = "http://Services.AnswerFinderWebService.knowology.com/", className = "com.knowology.km.AnswerFindClient.FindAnswerResponse")
	public String findAnswer(
			@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") String arg1);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "GetAnswerContentByAbsParas")
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "GetAnswerContentByAbsParas", targetNamespace = "http://Services.AnswerFinderWebService.knowology.com/", className = "com.knowology.km.AnswerFindClient.GetAnswerContentByAbsParas")
	@ResponseWrapper(localName = "GetAnswerContentByAbsParasResponse", targetNamespace = "http://Services.AnswerFinderWebService.knowology.com/", className = "com.knowology.km.AnswerFindClient.GetAnswerContentByAbsParasResponse")
	public String getAnswerContentByAbsParas(
			@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") String arg1);

}
