package com.knowology.km.NLPCallerWS;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "NLPCaller4WSDelegate", targetNamespace = "http://Services.NLPWebService.knowology.com/")
public interface NLPCaller4WSDelegate {

	/**
	 * 
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "KAnalyze")
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "KAnalyze", targetNamespace = "http://Services.NLPWebService.knowology.com/", className = "com.knowology.km.NLPCallerWS.KAnalyze")
	@ResponseWrapper(localName = "KAnalyzeResponse", targetNamespace = "http://Services.NLPWebService.knowology.com/", className = "com.knowology.km.NLPCallerWS.KAnalyzeResponse")
	public String kAnalyze(
			@WebParam(name = "arg0", targetNamespace = "") String arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "OldDetailAnalyze")
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "OldDetailAnalyze", targetNamespace = "http://Services.NLPWebService.knowology.com/", className = "com.knowology.km.NLPCallerWS.OldDetailAnalyze")
	@ResponseWrapper(localName = "OldDetailAnalyzeResponse", targetNamespace = "http://Services.NLPWebService.knowology.com/", className = "com.knowology.km.NLPCallerWS.OldDetailAnalyzeResponse")
	public String oldDetailAnalyze(
			@WebParam(name = "arg0", targetNamespace = "") String arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "DetailAnalyze")
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "DetailAnalyze", targetNamespace = "http://Services.NLPWebService.knowology.com/", className = "com.knowology.km.NLPCallerWS.DetailAnalyze")
	@ResponseWrapper(localName = "DetailAnalyzeResponse", targetNamespace = "http://Services.NLPWebService.knowology.com/", className = "com.knowology.km.NLPCallerWS.DetailAnalyzeResponse")
	public String detailAnalyze(
			@WebParam(name = "arg0", targetNamespace = "") String arg0);

	/**
     * 
     */
	@WebMethod(operationName = "UpdateKB")
	@RequestWrapper(localName = "UpdateKB", targetNamespace = "http://Services.NLPWebService.knowology.com/", className = "com.knowology.km.NLPCallerWS.UpdateKB")
	@ResponseWrapper(localName = "UpdateKBResponse", targetNamespace = "http://Services.NLPWebService.knowology.com/", className = "com.knowology.km.NLPCallerWS.UpdateKBResponse")
	public void updateKB();

	/**
     * 
     */
	@WebMethod(operationName = "InitKB4NLP")
	@RequestWrapper(localName = "InitKB4NLP", targetNamespace = "http://Services.NLPWebService.knowology.com/", className = "com.knowology.km.NLPCallerWS.InitKB4NLP")
	@ResponseWrapper(localName = "InitKB4NLPResponse", targetNamespace = "http://Services.NLPWebService.knowology.com/", className = "com.knowology.km.NLPCallerWS.InitKB4NLPResponse")
	public void initKB4NLP();

}
