package com.knowology.km.NLPCallerWS;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * NLPWebService service = new NLPWebService();
 * NLPCaller4WSDelegate portType = service.getNLPCallerWS();
 * portType.kAnalyze(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "NLPWebService", targetNamespace = "http://Services.NLPWebService.knowology.com/", wsdlLocation = "http://222.186.101.212:8282/NLPWebService/NLPCallerWS?wsdl")
public class NLPWebService extends Service {

	private final static URL NLPWEBSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(com.knowology.km.NLPCallerWS.NLPWebService.class
					.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.knowology.km.NLPCallerWS.NLPWebService.class
					.getResource(".");
			url = new URL(baseUrl,
					"http://222.186.101.212:8282/NLPWebService/NLPCallerWS?wsdl");
		} catch (MalformedURLException e) {
			logger
					.warning("Failed to create URL for the wsdl Location: 'http://222.186.101.212:8282/NLPWebService/NLPCallerWS?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		NLPWEBSERVICE_WSDL_LOCATION = url;
	}

	public NLPWebService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public NLPWebService() {
		super(NLPWEBSERVICE_WSDL_LOCATION,
				new QName("http://Services.NLPWebService.knowology.com/",
						"NLPWebService"));
	}

	/**
	 * 
	 * @return returns NLPCaller4WSDelegate
	 */
	@WebEndpoint(name = "NLPCallerWS")
	public NLPCaller4WSDelegate getNLPCallerWS() {
		return super.getPort(new QName(
				"http://Services.NLPWebService.knowology.com/", "NLPCallerWS"),
				NLPCaller4WSDelegate.class);
	}

}
