package com.knowology.km.NLPAppWS;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * AnalyzeEnterService service = new AnalyzeEnterService();
 * AnalyzeEnterDelegate portType = service.getAnalyzeEnterPort();
 * portType.analyze(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "AnalyzeEnterService", targetNamespace = "http://knowology.com/", wsdlLocation = "http://192.168.1.100:8080/NLPAppWS/AnalyzeEnterPort?wsdl")
public class AnalyzeEnterService extends Service {

	private final static URL ANALYZEENTERSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(com.knowology.km.NLPAppWS.AnalyzeEnterService.class
					.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.knowology.km.NLPAppWS.AnalyzeEnterService.class
					.getResource(".");
			url = new URL(baseUrl,
					"http://192.168.1.100:8080/NLPAppWS/AnalyzeEnterPort?wsdl");
		} catch (MalformedURLException e) {
			logger
					.warning("Failed to create URL for the wsdl Location: 'http://192.168.1.100:8080/NLPAppWS/AnalyzeEnterPort?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		ANALYZEENTERSERVICE_WSDL_LOCATION = url;
	}

	public AnalyzeEnterService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public AnalyzeEnterService() {
		super(ANALYZEENTERSERVICE_WSDL_LOCATION, new QName(
				"http://knowology.com/", "AnalyzeEnterService"));
	}

	/**
	 * 
	 * @return returns AnalyzeEnterDelegate
	 */
	@WebEndpoint(name = "AnalyzeEnterPort")
	public AnalyzeEnterDelegate getAnalyzeEnterPort() {
		return super.getPort(new QName("http://knowology.com/",
				"AnalyzeEnterPort"), AnalyzeEnterDelegate.class);
	}

}
