package com.knowology.km.webServiceClient;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * MsgQueueService service = new MsgQueueService();
 * MsgQueueDelegate portType = service.getMsgQueuePort();
 * portType.getName(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "MsgQueueService", targetNamespace = "http://service.DQ.knowology.com/", wsdlLocation = "http://localhost:8080/DeliveryQueue/MsgQueuePort?wsdl")
public class MsgQueueService extends Service {

	private final static URL MSGQUEUESERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(com.knowology.km.webServiceClient.MsgQueueService.class
					.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.knowology.km.webServiceClient.MsgQueueService.class
					.getResource(".");
			url = new URL(baseUrl,
					"http://localhost:8080/DeliveryQueue/MsgQueuePort?wsdl");
		} catch (MalformedURLException e) {
			logger
					.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/DeliveryQueue/MsgQueuePort?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		MSGQUEUESERVICE_WSDL_LOCATION = url;
	}

	public MsgQueueService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public MsgQueueService() {
		super(MSGQUEUESERVICE_WSDL_LOCATION, new QName(
				"http://service.DQ.knowology.com/", "MsgQueueService"));
	}

	/**
	 * 
	 * @return returns MsgQueueDelegate
	 */
	@WebEndpoint(name = "MsgQueuePort")
	public MsgQueueDelegate getMsgQueuePort() {
		return super.getPort(new QName("http://service.DQ.knowology.com/",
				"MsgQueuePort"), MsgQueueDelegate.class);
	}

}
