package com.knowology.km.webServiceClient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "MsgQueueDelegate", targetNamespace = "http://service.DQ.knowology.com/")
public interface MsgQueueDelegate {

	/**
	 * 
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getName", targetNamespace = "http://service.DQ.knowology.com/", className = "com.knowology.km.webServiceClient.GetName")
	@ResponseWrapper(localName = "getNameResponse", targetNamespace = "http://service.DQ.knowology.com/", className = "com.knowology.km.webServiceClient.GetNameResponse")
	public String getName();

	/**
	 * 
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "setName", targetNamespace = "http://service.DQ.knowology.com/", className = "com.knowology.km.webServiceClient.SetName")
	@ResponseWrapper(localName = "setNameResponse", targetNamespace = "http://service.DQ.knowology.com/", className = "com.knowology.km.webServiceClient.SetNameResponse")
	public void setName(
			@WebParam(name = "arg0", targetNamespace = "") String arg0);

	/**
	 * 
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getIp", targetNamespace = "http://service.DQ.knowology.com/", className = "com.knowology.km.webServiceClient.GetIp")
	@ResponseWrapper(localName = "getIpResponse", targetNamespace = "http://service.DQ.knowology.com/", className = "com.knowology.km.webServiceClient.GetIpResponse")
	public String getIp();

	/**
	 * 
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getMsg", targetNamespace = "http://service.DQ.knowology.com/", className = "com.knowology.km.webServiceClient.GetMsg")
	@ResponseWrapper(localName = "getMsgResponse", targetNamespace = "http://service.DQ.knowology.com/", className = "com.knowology.km.webServiceClient.GetMsgResponse")
	public String getMsg(
			@WebParam(name = "arg0", targetNamespace = "") MsgQueue arg0);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns com.knowology.km.webServiceClient.MsgQueue
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "createQueue", targetNamespace = "http://service.DQ.knowology.com/", className = "com.knowology.km.webServiceClient.CreateQueue")
	@ResponseWrapper(localName = "createQueueResponse", targetNamespace = "http://service.DQ.knowology.com/", className = "com.knowology.km.webServiceClient.CreateQueueResponse")
	public MsgQueue createQueue(
			@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") String arg1);

	/**
	 * 
	 * @param arg2
	 * @param arg1
	 * @param arg0
	 * @return returns int
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "sendMsg", targetNamespace = "http://service.DQ.knowology.com/", className = "com.knowology.km.webServiceClient.SendMsg")
	@ResponseWrapper(localName = "sendMsgResponse", targetNamespace = "http://service.DQ.knowology.com/", className = "com.knowology.km.webServiceClient.SendMsgResponse")
	public int sendMsg(
			@WebParam(name = "arg0", targetNamespace = "") MsgQueue arg0,
			@WebParam(name = "arg1", targetNamespace = "") String arg1,
			@WebParam(name = "arg2", targetNamespace = "") String arg2);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getMsgById", targetNamespace = "http://service.DQ.knowology.com/", className = "com.knowology.km.webServiceClient.GetMsgById")
	@ResponseWrapper(localName = "getMsgByIdResponse", targetNamespace = "http://service.DQ.knowology.com/", className = "com.knowology.km.webServiceClient.GetMsgByIdResponse")
	public String getMsgById(
			@WebParam(name = "arg0", targetNamespace = "") MsgQueue arg0,
			@WebParam(name = "arg1", targetNamespace = "") String arg1);

	/**
	 * 
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "setIp", targetNamespace = "http://service.DQ.knowology.com/", className = "com.knowology.km.webServiceClient.SetIp")
	@ResponseWrapper(localName = "setIpResponse", targetNamespace = "http://service.DQ.knowology.com/", className = "com.knowology.km.webServiceClient.SetIpResponse")
	public void setIp(@WebParam(name = "arg0", targetNamespace = "") String arg0);

}
