/*
 * File: app/model/synonymModel.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.model.synonymModel', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.Field'
    ],

    fields: [
        {
            name: 'id',
            type: 'string'
        },
        {
            name: 'synonym',
            type: 'string'
        },
        {
            name: 'type',
            type: 'string'
        },
        {
            name: 'worditem',
            type: 'string'
        },
        {
            name: 'wordclass',
            type: 'string'
        },
        {
            name: 'wordid',
            type: 'string'
        },
        {
            name: 'stdwordid',
            type: 'string'
        },
        {
            name: 'isInclude',
            type: 'boolean'
        }
    ]
});